name: "ukidacdevauth"
fqdn: "rsp-dev.lsst.ac.uk"
appOfAppsName: "science-platform"
vaultUrl: "https://vault-rsp.lsst.ac.uk"
vaultPathPrefix: ""secret/phalanx/ukidacdevauth"
applications:
  postgres: true
  squareone: true
