name: "rspwfau"
fqdn: "wfau.lsst.ac.uk"
appOfAppsName: "science-platform"
vaultUrl: "https://vault-rsp.lsst.ac.uk"
vaultPathPrefix: "secret/phalanx/rspwfau"
applications:
  postgres: true
  squareone: true
  nublado: true
