redis:
  persistence:
    enabled: false

config:
  internalDatabase: true

  oidcServer:
    enabled: true

  updateSchema: false

  github:
    clientId: "Ov23li82U9NKJqgcXMNf"


# Support generating user metadata for CADC authentication code.
#  cadcBaseUuid: "4cb5f948-aad9-466c-837b-5eae565b0a77"

# Allow access by GitHub team.
  groupMapping:
    "admin:userinfo":
      - github:
          organization: "wfau"
          team: "trsp-dev"
    "exec:admin":
      - github:
          organization: "wfau"
          team: "trsp-dev"
    "exec:internal-tools":
      - github:
          organization: "wfau"
          team: "trsp-dev"
    "exec:notebook":
      - github:
          organization: "wfau"
          team: "trsp-dev"
    "exec:portal":
      - github:
          organization: "wfau"
          team: "trsp-dev"
    "exec:portal-admin":
      - github:
          organization: "wfau"
          team: "trsp-dev"
    "read:image":
      - github:
          organization: "wfau"
          team: "trsp-dev"
    "read:tap":
      - github:
          organization: "wfau"
          team: "trsp-dev"

  initialAdmins:
    - "lelliott"
