redis:
  persistence:
    enabled: false

config:
  internalDatabase: true
  
  oidcServer:
    enabled: true

  updateSchema: true
  
  oidc:
    clientId: "rsp-dev"
    audience: "rsp-dev"
    loginUrl: "https://aai-dev.lsst.ac.uk/realms/lsst/protocol/openid-connect/auth"
    tokenUrl: "https://aai-dev.lsst.ac.uk/realms/lsst/protocol/openid-connect/token"
    issuer: "https://aai-dev.lsst.ac.uk/realms/lsst"
    scopes:
      - "openid"
    usernameClaim: "preferred_username"

  ldap:
    url: "ldap://aai-dev.lsst.ac.uk"
    userDn: "cn=admin,dc=dev,dc=lsst,dc=ac,dc=uk"
    userBaseDn: "ou=users,dc=dev,dc=lsst,dc=ac,dc=uk"
    uidAttr: "uidNumber"
    gidAttr: "gidNumber"
    groupBaseDn: "ou=groups,dc=dev,dc=lsst,dc=ac,dc=uk"
    groupMemberAttr: "memberUid"
    groupSearchByDn: false

  oidcServer:
    enabled: false

  groupMapping:
    "admin:userinfo":
      - "rsp"
      - "rsp"

  initialAdmins:
    - "test1"

    
    
